/**
 * @file CityReport.h
 *
 * @author Aiden Dixon
 *
 * The city report is generated by the members of the city.
 * It is a collection of objects of type MemberReport.
 */

#pragma once

#include <memory>
#include <vector>
#include <random>
#include <list>

class City;
class MemberReport;

/**
 * The city report is generated by the members of the city.
 * It is a collection of objects of type MemberReport.
*/
class CityReport
{
private:
    /// The city this report is for
    City* mCity;

    /// Random number generator
    std::mt19937 mRandom;

protected:
    /// Size of the bins in the linked list
    static const int BinSize = 7;




    /// A bin stores up to 7 city reports in a
    /// single linked list node.
    class ReportsBin {
    public:
        /// A place to store the reports in this bin
        /// Up to 7 reports can be stored, followed by
        /// a null pointer after the last report pointer.
        std::shared_ptr<MemberReport> mReports[BinSize+1];




        bool IsFull();
        void Add(std::shared_ptr<MemberReport> report);

    };

    /// The collection of reports
    std::list<std::shared_ptr<ReportsBin>> mReportBins;

public:
    explicit CityReport(City* city);

    void Add(std::shared_ptr<MemberReport> report);

    /** Iterator that iterates over the the Reports */
    class Iter
    {
    private:
        /// CityReport we are iterating over
        CityReport *mCityReport;

        /// Iterator over bins list
        std::list<std::shared_ptr<ReportsBin>>::iterator mBinsIterator;

        int mReportPos;

    public:

        /** Constructor
        * @param collection The collection we are iterating over */
        Iter(CityReport *cityReport, std::list<std::shared_ptr<ReportsBin>>::iterator bins, int reportPos) :
               mCityReport(cityReport), mBinsIterator(bins), mReportPos(reportPos)  {}

        /**
        * Get value at current position
        * @return current report in the collection
        */
        std::shared_ptr<MemberReport> operator *() const {return (*mBinsIterator)->mReports[mReportPos];}


        /**
         * Test for end of the iterator
         * @param other The other iterator we are comparing with
         * @return True if we this position equals not equal to the other position
         */
        bool operator!=(const Iter &other) const
        {
            return mBinsIterator != other.mBinsIterator || mReportPos != other.mReportPos;
        }
        /**
         * Increment the iterator
         * @return Reference to this iterator
         * */
        const Iter& operator++()
        {
            ///Increments mReportPos
            if ((*mBinsIterator)->mReports[++mReportPos] == nullptr)
            {
                mBinsIterator++;
                mReportPos = 0;
            }
            return *this;

        }
    };

    /**
    * Get an iterator for the beginning of the collection
    * @return Iter object for the beginning of the collection
    */
    Iter begin() { return Iter(this, mReportBins.begin(), 0  ); }

    /**
     * Get an iterator for the end of the collection
     * @return Iter object for the end of the collection
     */
    Iter end() { return Iter(this, mReportBins.end(), 0  );}
};

